### ISSUE TITLE
Refactor ASTBuilder

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#29]

**Comment by danielsun1106** [comment]
Statement parsing code refactored: https://github.com/jespersm/groovy/commit/5144176c4fdafc5b9b32feac1714dac0716194b2

**Comment by jespersm** [comment]
I'm not sure I follow the way this is going - Basically class-per-grammar-rule, with dynamic class loading based on name?
As I see it, this is going to make refactoring harder, not easier.

**Comment by daniellansun** [comment]
Currently just quite a little of refactoring is done. As you see, fine-grained management of rule processing is the target, which can help us separate concern points.
Yeah, it's a hard work but I will try my best to complete ;-)

**Comment by danielsun1106** [comment]
expression and some other parsing code refactored: https://github.com/jespersm/groovy/commit/9cb656a9d34052178793ac8c009cc4283a17552e

BTW, the refactoring really need quite some work. The left rule parsing code will be refactored in the next commits.

**Comment by daniellansun** [comment]
@jespersm 
It seems that we have different opinions on the refactoring on ASTBuilder. In order to work on the same direction, I have reverted all the recfactoring. So it's not necessary to have the antlr4-no-refactor branch ;-)

**Comment by jespersm** [comment]
Well, we should ideally ask the dev list for advice, since it's going to be maintained by many different people going forward.

**Comment by daniellansun** [comment]
Yeah, I agree with you. There're a lot of other emergent tasks waiting us to complete ;-)

**Comment by blackdrag** [comment]
is it possible to implement a visitor using the GroovyParser context classes? Such a visitor could be interesting for more than just building the AST. Then you could base the AST builder on that visitor... though it is more a converter than really a builder actually

**Comment by daniellansun** [comment]
@blackdrag 
Jochen, do you mean that we implement our own visitor based on the visitor generated by antlr4? If yes, we can clean the "instanceof" codes but our visitor is still very big...

**Comment by jespersm** [comment]
@blackdrag Yes, Antlr4 supports generating a visitor and/or a listener from the grammar, and I'm not sure why @xSeagullx didn't go with those, but I think it was to keep the parser's context information free of the ASTNode types.
The listener approach would allow us to drop the parse tree while parsing, potentially reducing heap usage.

**Comment by blackdrag** [comment]
@jespersm in the current part, we have a visitor for the antlr part, it is used for the java2groovy tool for example. But otherwise it is not used much. What I had in mind is a visitor working with the antlr classes, a builder for the AST and an orchestring part, that is an implementation of that visitor, which uses the builder to produce the AST. That's kind of what AntlrParserPlugin does today

@danielsun1106 the question is what is better, a big class, with many methods, or many classes with a few methods. I do prefer the first case, because you safe on boilerplate code, and you have not to look at dozens of classes, plus changes in that area will not effect dozens of files all at once. But that is probably more about personal preferences.

In the end I will leave that to you guys, since you do the implementation. Do what you feel more comfortable with.
