### ISSUE TITLE
Closure call does not support

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#40]
```
def a = {return 1}()

{x, y-> return x + y} (1, 2)

{x, y-> return x + y} 1, 2

{x, y-> return x() + y()} {1} {2}

{x, y-> return x + y()}(1) {2}
```

**Comment by daniellansun** [comment]
My stashed fix can not pass the following test case:
a b c d, {->}, {->} d e({->}, {->})

Supporting closure call add ambiguities to the current syntax...
Maybe I should add some constraints on it.

**Comment by daniellansun** [comment]
I notice that the test case is related to command expression of Groovy.

@blackdrag Jochen, could you tell me the syntax of command expression? Thanks in advance.

``` groovy
a b c d, {->}, {->} d e({->}, {->})
```

``` antlr
cmdExpressionRule: pathExpression ( argumentList IDENTIFIER)* argumentList IDENTIFIER? ;
```

**Comment by daniellansun** [comment]
It seems that I found a useful article(http://mrhaki.blogspot.com/2011/05/groovy-goodness-command-chain.html).

**Comment by blackdrag** [comment]
I would probably have said 
`cmdExpressionRule: pathExpression argumentList (IDENTIFIER argumentList)* IDENTIFIER?;` If we want to cover normal method calls and command expressions, then the rule I just wrote, I guess... of course argumentList here means optional parens. In the old grammar you will see, that I made the argumentlist reading part greedy to resolve the conflict with IDENTIFIER, since that can be then resolved to argumentlist as well. which is also why I set the parans in the grammar here different.
Of course the version not covering normal method calls would be `pathExpression argumentList (IDENTIFIER argumentList)+ IDENTIFIER?` then

**Comment by daniellansun** [comment]
Jochen, thanks for your detail reply. I think I have understood the command expressions.
BTW, I use implicitThisCallExpression rule to cover normal method calls, implicitThisCallExpression is not a good name... I'll rename it later(e.g. normalCallExpression?)

**Comment by daniellansun** [comment]
Fixed by: https://github.com/jespersm/groovy/commit/2070f2e5d11f5f02c4daba4019e33d3c472f3943
