### ISSUE TITLE
Refactor cmdExpressionRule by referencing callExpressionRule

### ISSUE THREAD

**Issue by daniellansun** [jespersm/incubator-groovy#43]

**Comment by daniellansun** [comment]
I tried to deactive the clsoure call alternative by semantic predicate, but ANTLR4 still recognize "foo(arg1, arg2) {->} {->}" as a cmd expression and failed to create the right parse tree. I'm not sure  whether it is ANTLR4's bug? 

@jespersm 
Any idea about it?

``` antlr
callExpressionRule: (selectorName | STRING | gstring | { isClosureCallEnabled() }? c=closureExpressionRule) LPAREN argumentList? RPAREN closureExpressionRule*
                  | { !GrammarPredicates.isFollowedByLPAREN(_input) }? (selectorName | STRING | gstring | { isClosureCallEnabled() }? c=closureExpressionRule) argumentList
                  ;

cmdExpressionRule
@init {
    disableClosureCall();
}
@after {
    enableClosureCall();
}
: (expression op=(DOT | SAFE_DOT | STAR_DOT))? c=callExpressionRule callExpressionRule+ prop=IDENTIFIER? ;

```

**Comment by jespersm** [comment]
I think this is going the wrong way, with too much rule duplication and semantic predicates. I'll give it a try.

**Comment by daniellansun** [comment]
@sharwell
Hi Sam,

```
 I found semantic predicates failed to deactive alternative of rule sometimes and generated a parse tree that we did not expect(sometimes failed to parse at all).

 What I wish is when the alternative of rule is deactived by semantic predicates, antlr4 can treat the deactived alternative as if it does not exist(or be removed).

 Could you please tell me whether I misunderstand the usage of semantic predicates?
```

Thanks in advance,
Daniel.Sun

**Comment by daniellansun** [comment]
@sharwell
    If I remove the alternative to deactive, antlr4 can parse the input text properly. But if I use semantic predicates to deactive the alternative, antlr4 fails to parse. The question confused me for a long time...I don't know why...

**Comment by sharwell** [comment]
You can't used `@init` and `@after` blocks to drive state for semantic predicates, because semantic predicates are evaluated before they are considered. Rather, you need to pass the flag as an argument to the rule.

:memo: In the following rules, the semantic predicates in `callExpressionRule` will be _automatically disabled_ (treated as true) when performing predictions everywhere except within `callExpressionRule` itself. This is a limitation of ANTLR 4; if you write rules in such a way that this rule is violated you will receive a `PredicateFailedException` (or something like that) at runtime.

``` antlr
callExpressionRule[boolean closureCallEnabled]
  : ( selectorName
    | STRING
    | gstring
    | {$closureCallEnabled}? c=closureExpressionRule
    ) LPAREN argumentList? RPAREN closureExpressionRule*
  | { !GrammarPredicates.isFollowedByLPAREN(_input) }?
    ( selectorName
    | STRING
    | gstring
    | {$closureCallEnabled}? c=closureExpressionRule
    ) argumentList
  ;

cmdExpressionRule
  : (expression op=(DOT | SAFE_DOT | STAR_DOT))?
    c=callExpressionRule[false]
    callExpressionRule[false]+
    prop=IDENTIFIER?
  ;
```

**Comment by sharwell** [comment]
Also note that the `@baseContext` functionality is intended to provide a better alternative to this:

```
callExpressionRule_noClosure
@baseContext{callExpressionRule}
  : ( selectorName
    | STRING
    | gstring
    ) LPAREN argumentList? RPAREN closureExpressionRule*
  | { !GrammarPredicates.isFollowedByLPAREN(_input) }?
    ( selectorName
    | STRING
    | gstring
    ) argumentList
  ;
```

The above rule can be referenced instead of `closureCallEnabled[false]`, always works for prediction, and uses the `@baseContext` action to instruct the code generator to create a `CallExpressionRuleContext` for it instead of the default `CallExpressionRule_noClosureContext`.

**Comment by daniellansun** [comment]
@sharwell
Hi Sam,
    Thanks for your valuable suggestions and examples! I'll keep them in mind.
    In addition, could you tell me why I can't deactive alternatives sometimes simply by semantic predicate {false}? 
    Some days ago, I tried to check whether deactivating alternative would work, so I simply replaced { isClosureCallEnabled() }?  with {false}? . As a result, antlr4 still failed to parse, but when I removed the alternative to deactive, antlr4 can parse the same input text.

**ORIGINAL ALTERNATIVE OF RULE**
{ !GrammarPredicates.isFollowedByLPAREN(_input) }? (selectorName | STRING | gstring | { isClosureCallEnabled() }? c=closureExpressionRule) argumentList;

**EXPERIMENTAL ALTERNATIVE OF RULE**
{ !GrammarPredicates.isFollowedByLPAREN(_input) }? (selectorName | STRING | gstring | **{ false }?** c=closureExpressionRule) argumentList;

Thanks in advance,
Daniel.Sun

**Comment by sharwell** [comment]
Semantic predicates are only executed on the left edge of decisions. For example, the following will fail to parse the input `aa`:

```
start
  : 'a' ({false}? 'a' | 'b')
  | 'a' 'a'
  ;
```

Before consuming the first `a`, the semantic predicate is ignored because it is not on the left edge. Since the input `aa` appears to work with the first and second alternative equally, it chooses the first alternative. Only after choosing the first alternative will it get to a decision where the predicate is considered, but by then it's already down an incorrect path.

:memo: Semantic predicates are _much_ more predictable in lexer rules. However, we still recommend avoiding them where possible due to their performance overhead. If they can't be avoided, it helps to at least move them one or more symbols to the right in lexer rules to avoid performance overhead. For example, the following two rules match the same inputs, but the second is _much_ faster.

``` antlr
// This will slow down the entire lexer, not just tokens starting with '/*'
SLOW
  : {_input.LA(3)=='*'}? '/*'
  ;

// The predicate here is *only* evaluated where the input is '/*'
FAST
  : '/*' {_input.LA(1)=='*'}?
  ;
```

**Comment by daniellansun** [comment]
@sharwell
Hi Sam,
Thanks for your detailed reply!
May I ask one more question. The following grammar code is modified from your example. I tried input double a separated by a white space: a a
Antlr4 reports: no viable alternative at input 'a'
Could you please tell me why the alternative of sub rule failed to be deactivated? 
**FAILED(deactivate the alternative by semantic predicate)**
grammar Sp;
start : expr EOF;
expr : A sub
         | A A
         ;
sub : {false}? A
        | B
        ;
A :   'a';
B :   'b';
WS : [ \t\r\n]+ -> skip;

**SUCCEED(remove the alternative)**
grammar Sp;
start : expr EOF;
expr : A sub
         | A A
         ;
sub : B
        ;
A :   'a';
B :   'b';
WS : [ \t\r\n]+ -> skip;

Thanks in advance,
Daniel.Sun

p.s. edited on my cell phone. shame on less styles for codes.

**Comment by danielsun1106** [comment]
@sharwell
Hi Sam,
Thanks for your detailed reply!
May I ask one more question. The following grammar code is modified from your example. I tried input double a separated by a white space: a a
Antlr4 reports: no viable alternative at input 'a'
Could you please tell me why the alternative of sub rule failed to be deactivated? 
**FAILED(deactivate the alternative by semantic predicate)**
grammar Sp;
start : expr EOF;
expr : A sub
         | A A
         ;
sub : {false}? A
        | B
        ;
A :   'a';
B :   'b';
WS : [ \t\r\n]+ -> skip;

**SUCCEED(remove the alternative)**
grammar Sp;
start : expr EOF;
expr : A sub
         | A A
         ;
sub : B
        ;
A :   'a';
B :   'b';
WS : [ \t\r\n]+ -> skip;

Thanks in advance,
Daniel.Sun

p.s. edited on my cell phone. shame on less styles for codes.

**Comment by blackdrag** [comment]
frankly I would have expected a rule like this

```
pathOperator:  DOT | SAFE_DOT | STAR_DOT | ATTR_DOT | MEMBER_POINTER
pathExpression: expression (pathOperator expression)*
argumentsWithOptionalParen: (LPAREN argumentList? RPAREN) | argumentList:
callExpressionRule : pathExpression argumentsWithOptionalParen;
cmdExpressionRule: callExpressionRule+;
```

where argumentList contains closureExpressionRule+ as alternative for each element of the list as well as selectorName, STRING and GSTRING. cmdExpressionRule is used instead of callExpressionRule, ot as alternative

**Comment by daniellansun** [comment]
Jochen, I am not sure whether I fully understand your last words "cmdExpressionRule is used instead of callExpressionRule, ot as alternative", could you clarify for us?

**Comment by daniellansun** [comment]
BTW, callExpressionRule should also be an expression, but the suggested version of callExpressionRule starts with expression, which is indirect resursive and not accepted by antlr4...

**Comment by sharwell** [comment]
@danielsun1106 the **com.tunnelvisionlabs** build of ANTLR 4 supports indirect left recursion (I believe the 4.5 build you are using already includes this feature). It still doesn't support _hidden_ left recursion, but if your recursion is truly on the left edge of your rules then it should work.

This should work with this release:

``` antlr
working
  : 'a'
  | expression 'a'
  ;

expression
  : working 'b'
  ;
```

However this still will not work, because the invocation of `expression` inside of `not_working` does not appear on the left side of a decision.

``` antlr
not_working
  : 'a'? expression
  | 'c'
  ;

expression
  : not_working
  | 'b'
  ;
```

**Comment by daniellansun** [comment]
@sharwell
Awesome! The book I read before is a bit outdated :-)
BTW, could you answer my question asked about 10 hours ago? The failed version choose wrong alternative to consume input text, and no backtrack available in the antlr4, so antlr4 will not try to find other parsing path. I am not sure whether I understand the ALL(*) parsing strategy properly...Thanks in advance.

**Comment by sharwell** [comment]
ANTLR 4 only considers predicates which appear on the left edge of a decision. For example, the following rule (in isolation) will work as expected:

> :memo: The following descriptions apply only to _parser_ rules. Predicates in lexer rules are evaluated regardless of where they are placed.

``` antlr
start
  : {false}? 'a' 'a' EOF
  | 'a' 'a' EOF
  ;
```

However, if you move the predicate so a terminal appears before it, it will be ignored:

``` antlr
start
  : 'a' {false}? 'a' EOF
  | 'a' 'a' EOF
  ;
```

If you encounter a case like this, it is actually detectable with ANTLR 4. One of the following will have occurred:

### A context sensitivity

In this case, SLL made the wrong decision but enabling LL will result in a correct decision. In some cases, simply reordering alternatives will allow the SLL parsing to succeed. For example, if the second rule above were written as follows, parsing would succeed:

``` antlr
start
  : 'a' 'a' EOF
  | 'a' {false}? 'a' EOF
  ;
```

### An ambiguity

The remedy for this is often similar to the previous case (reordering alternatives may allow SLL parsing to succeed), but unlike a context sensitivity it is possible for for LL parsing to make an incorrect decision. If you turn the prediction mode to `PredictionMode.LL_EXACT_AMBIG_DETECTION`, you can use a diagnostic error listener to identify ambiguities in prediction.

> :memo: Not all predicates are evaluated in all cases while making predictions in parser rules. A grammar may be identified as ambiguous if the only disambiguation is semantic predicates, and those predicates happen to be ignored for a decision.

### An actual incorrect input

If the input is erroneous and/or the grammar is missing support for an intended language feature, you will of course receive a parse error regardless of the way predicates are evaluated.

**Comment by daniellansun** [comment]
@sharwell 
     Sam, as we see, the following semantic predicate`{false}?` is truely on the left edge of a decision, but antlr4 still fails to parse `a a`(double a seprated by a white space). The reason I guess antlr4 choose the first alternative of expr rule, consumed the first `a`, when it tried to consume one more `a`, the alternative of sub rule is deactived`{false}? A`, but antlr4 is already down an incorrect path that time(and no backtrack available in the antlr4), so it will not try to find other parsing path(such as the 2nd alternative of expr `A A`). Do I understand properly?Thanks in advance.

**sub rule:**

``` antlr
sub : {false}? A
       | B
       ;
```

**complete grammar(failed, deactive the alternative):**

``` antlr
grammar Sp;
start : expr EOF;
expr : A sub
        | A A
        ;
sub : {false}? A
       | B
       ;
A : 'a';
B : 'b';
WS : [ \t\r\n]+ -> skip;
```

**complete grammar(succeeded, remove the alternative):**

``` antlr
grammar Sp;
start : expr EOF;
expr : A sub
        | A A
        ;
sub : B
       ;
/*
sub : {false}? A
       | B
       ;
*/
A : 'a';
B : 'b';
WS : [ \t\r\n]+ -> skip;
```

**Comment by sharwell** [comment]
I think you have it figured out here. :smile:

The predicate is on the left edge of one decision (the main decision in the rule `sub`), but that is not the only decision in the grammar. In particular, the predicate is _not_ on the left edge of the decision in `expr`, and that is the decision which is made incorrectly as a result.

**Comment by daniellansun** [comment]
@sharwell
I see. Thanks very much for your answering my so many questions which confused me for quite a long time :-)

**Comment by sharwell** [comment]
No problem. If you use `@baseContext{}` or indirect left recursion functionality, please keep in mind that both are in their early stages and I'd value your feedback regarding how they work out for you. :smile:

**Comment by daniellansun** [comment]
I'll try these new features during developing the new parser for Groovy programming language. They will be very useful to simplify the grammar codes. Thanks again!

**Comment by blackdrag** [comment]
**"cmdExpressionRule is used instead of callExpressionRule:**
I mean there should be no rule alternatives like this:

```
someRule: cmdExpressionRule | callExpressionRule;
```

**callExpressionRule should also be an expression, but the suggested version of callExpressionRule starts with expression, which is indirect resursive and not accepted by antlr4:**
yeah... you did know Groovy allows this one?:  `(1+1).("a"+1)() // call 2.a1()`? Or a command expression version: `(1+1).("a"+1) a b c` In the old grammar some parts are greedy, which is why  `1+1.("a"+1)()` tries to call a1 on 1 instead of 2. In a similar way `(1+1)."a"+1()` would try to get property a on 2 and then do 1.call() to later add the results. So if no greedy mode is supposed we used I think making a difference between expression in parens plus simple expressions and complex expressions not in parens would work. A complex expression would be anything with an operator for example. So eomthing like:

```
expression: expressisonInParens | expressionsWithOperator | pathExpresion | callExpressionRule | ...;
expressisonInParens : LPAREN expression RPARAN | anyLiteral ....; // including GString and identifier
pathExpression: expressisonInParens (pathOperator expressisonInParens)*;
```

and so on

**Comment by daniellansun** [comment]
@blackdrag 
Though I have used Groovy since 2006(Groovy 1.0 beta version), I don't know and never try to write code like the sample `(1+1).("a"+1)()`  :astonished:

**Comment by jespersm** [comment]
@blackdrag: Antlr4's precedence rules **should** allow not breaking the expression rule up for this, but we need to generalize the RHS compared to what we have now. In other words "greedy or not" should follow precedence rules.

**Comment by jespersm** [comment]
I withdraw my last comment. I fear we have to explode the expression grammar to properly parse certain constructs, so that we can differentiate where in the precedence hierarchy we want to use certain parts. Example: "(int)1" is hard to differentiate from "((int)) 1" (meaning "int.class.call(1)"), since 'int' is a valid value.
We should be able to do away with some of the conditionals, then.

**Comment by daniellansun** [comment]
@blackdrag 
Jochen, It seem that I have understood your words a bit. cmdExpressionRule is actually a generalized version of callExpressionRule. If we use the recursive version of current callExpressionRule to implement cmdExpressionRule, maybe it will behave differrently with the old parser's version in some situations.
Could you offer us some concrete example code of cmd expression which may make differrences between new and old parsers? Thanks in advance.

**Comment by daniellansun** [comment]
@jespersm
Maybe semantic predicates can come to rescue.

**Comment by daniellansun** [comment]
I tried many times to refactor the command expression, but it is not that easy to complete according Jochen's advice, which I also think is ideal though. At last, I refactored and refined command expression by the following commits:
https://github.com/jespersm/groovy/commit/637b850c5bc3233f6dc3df52c1d0a8d3fbb19474
https://github.com/jespersm/groovy/commit/46638d68e111ed7eda14e0ece920b470dbf7026c
https://github.com/jespersm/groovy/commit/337350e1b5a4083ec1647796ee92708fe95ca6bc
https://github.com/jespersm/groovy/commit/15860938c4b7b692898d4e355daba39e59286017

@sharwell @parrt
`@baseContext {}` seems not be fully supported in the antlr4.5.3, maybe it's due to PR(https://github.com/antlr/antlr4/pull/697) not merged. I can write code like `@baseContext{callExpressionRule}`, but antlr4.5.3 does not generate `CallExpressionRuleContext`.

**Comment by danielsun1106** [comment]
Refactor further: https://github.com/jespersm/groovy/commit/337350e1b5a4083ec1647796ee92708fe95ca6bc

**Comment by sharwell** [comment]
@danielsun1106 The `@baseContext` action is a unique feature of the optimized fork of ANTLR 4 (the one with groupId **com.tunnelvisionlabs**). It is not available in the reference release of ANTLR.

**Comment by daniellansun** [comment]
@sharwell
Thanks, I see. It's quit a pity that the great feature has not been merged to the usual ANTLR 4 we are using.
